matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      before_install:
        - pyenv global 3.7.1
        - pip install -U pip
        - pip install awscli
      install:
        - mvn clean install -P aws -DskipTests
      before_deploy:
        - cp -Rf 'bp-web-ws/target/bp-web-ws.jar' bytepushers-bpweb-lambda-jar
      deploy:
        - provider: cloudformation
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: us-east-2
          wait: true
          template: bp-web-ws/aws-cloudformation/cloud-formation-deployment-bucket-template.yaml
          stack_name: bytepushers-bp-web-deployment-bucket
          parameters:
            - BucketName=${S3_DEPLOYMENT_BUCKET}
          capabilities: [ CAPABILITY_NAMED_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND ]
          edge: true
          skip_cleanup: true
          on:
            branch: develop
        - provider: s3
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          bucket: ${S3_DEPLOYMENT_BUCKET}
          region: us-east-2
          skip_cleanup: true
          glob: 'bytepushers-bpweb-lambda-jar'
          edge: true
          on:
            branch: develop
        - provider: cloudformation
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: us-east-2
          wait: true
          template: bp-web-ws/aws-cloudformation/cloud-formation-template.yaml
          stack_name: bytepushers-bp-web-ws
          parameters:
            - BucketName=${S3_DEPLOYMENT_BUCKET}
          capabilities: [CAPABILITY_NAMED_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND]
          edge: true
          skip_cleanup: true
          on:
            branch: develop
        - provider: script
          script:  aws lambda update-function-code --publish --function-name bytepushers-bpweb-ws --s3-bucket com.bytepushers.bpweb.ws --s3-key bytepushers-bpweb-lambda-jar --region us-east-2
          on:
            branch: develop
        - provider: script
          script: mvn clean deploy -P aws -DskipTests
          on:
            branch: master
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
