matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      deploy:
        - provider: script
          script: mvn clean deploy -P aws
          on:
            branch: feature/production-deployment
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
