matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      install:
        - mvn clean install -P aws -DskipTests
      before_deploy:
        - cp -Rf 'bp-web-ws/target/bp-web-ws.jar' bytepushers-bpweb-lambda-jar
      deploy:
        - provider: cloudformation
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          region: us-east-2
          wait: true
          template: bp-web-ws/cloud-formation-template.yaml
          stack_name: bytepushers-bp-web-ws
          capabilities: [CAPABILITY_NAMED_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND]
          edge: true
          skip_cleanup: true
          on:
            branch: develop
        - provider: s3
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          bucket: ${S3_DEPLOYMENT_BUCKET}
          region: us-east-2
          skip_cleanup: true
          glob: 'bp-web-ws.jar'
          edge: true # opt in to dpl v2
          on:
            branch: develop
        - provider: script
          script: mvn clean deploy -P aws -DskipTests
          on:
            branch: master
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
