language: bash
sudo: required
services:
- docker
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - make dockerpush
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - jsurya352@gmail.com
    on_success: always
    on_failure: always