matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      deploy:
        - provider: cloudformation
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          template: cloud-formation-template.yaml
          stack_name: bytepushers-bp-web-ws
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
