matrix:
  include:
    - language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      deploy:
        provider: script
        script: mvn clean deploy -P aws
        on:
          branch: develop
      env:
        - secure: FuLSvzcH/7Sjx0LMzn1JTAjKdig+CFpGjJNXNKq09y23NYbWkrHT2HVmEg1Sfx8ZZoKzgawSpeZCH7PgbYzKI1hcbq16jyJFhCszklEPVuyMj0+OmZTCum5+tCxK2nLnwRPpcRjRrgUEDRqQz8lvLyuwZA2IOvuHvtD+3+LP+XvaaKF9+CYamvtgNARb5fsTlmAsQT2jostBSpC46/ipMJpoDsWsgubHcpNED9I6DrtdIX3xK0AiG4EUIlpHiXEj++qFVyynLQnakKZfHjQ1I+BZqON/OPex1ivPUsqSaT2izvYUqWwUMmL38MOG1tcQpAN5dGza3tIaScW+Sjw70GpjEHyg3IWvWDr0eJnyP4x0d8uRnw6kJZvJvPXFBWiLubDRhQ2SA3/SDQNfUnnEqcgRhB+K51Rf7Z4YUfqpKqei86gG0jTZw7AhAnsJwpjGN51YJv0saNC0/i1MUkWi3Tr9q1jT39RE03bYhVSRoEhDvNZUGsMwY5sCOMvy2/9LZGKXJZOqaRKxrpQkjWkhKkwQ/Dy5feETVHKICYsabPujhUtDWgOZgXkprDrkP+fzWoWz6y2ehNKgPHrGk2hmcwZHAAOtEUwcdQoMo3iAMLM3uHu1ja4fd/lwgDBdYiAPVli4UvuXG1GJpaHmDukjYIpt9riSlm3+XEVLNsJJGGo=
        - secure: edZdifT3gNEWUL56bI6RJ+QaIgR01Kh3ZjGWYD47hdnN4v64ArqhMeyYLxpm6g0DjvM4CEkDdVADk6W1Gx9quM12EoYaeF7r4j9DKDgMP+GQuL0VPULDHYEkHnYD4d2hTFbN1naWhHAzrRTppmuGY5XUOL9IXiExqXhfBUxsT59EuuaL+oawW1C+YooTOrm1l1cS9KJWDt0aykf1lIFYf9sOr7l/N9OTGfpYoru4D9SXveRhNcf+SfEr+P+rwBg8XBNY6K/GXDhri6MXMc5XNvb7L+1glyIxz6qhmKQwlEV+j/wSKT9bDWVnkEOTzyUdOXG7UMDsuuW6H2U2aSw4FNRXYTs4JgeSngbYoLcCaUs8dCy76zlpdw7BjxuJ4c5XojNMXE+hRd6k31LTOEckXjKyJNCnFEB2co3+eIyiyZvlSim5dLgqumuVY5caZqKlovbPyog26sE14hVH8lwBA1aXQ9Zd82QuqpSctY3e5JMcdkeJod3pvmfrzKVyWGJh69dTZk+RFlTM5uTP/+1c2aHitph8kae1Mk9gxii/hSHHImqqBIQE11LT79yq2csFH+dqfEiUIx7lNh98BadponJ8g+uiPVjPWBfy8VpltmZZg3VBKAteZ+qoNHv78oj0uLzT9Oyk5l+igt8gHivs22ZmmY+NSrFsOHWdrExPxJs=
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - amanjotabroljava@gmail.com
    on_success: always
    on_failure: always
