AWSTemplateFormatVersion: '2010-09-09'
Description: BytePusher Webservice Deployment Bucket
Parameters:
  BucketName:
    Type: String
    Description: "AWS Lambda deployment bucket"
    Default: ""
Resources:
  BpWebServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: 'Enabled'