AWSTemplateFormatVersion: '2010-09-09'
Description: BytePusher Webservice Deployment Bucket
Resources:
  BpWebServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com.bytepushers.bpweb.ws
      VersioningConfiguration:
        Status: 'Enabled'