services:
  bp-web:
    container_name: bp-web-angular-app-container
    build: .
    image: tontepouncil/bp-web:latest
    ports:
      - 80:4000
    expose:
      - 80
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
