pring.profiles.active=no-db
application.security.token=bpweb3bpweb3bpwebbpwe3bbpwebbpwebbpwebb3pwebbpwebbpwebbp3webbpweb
spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
bp.web.hubspot.developerKey=